name: Node CI

on: [push]

      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]

      needs: build
